/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.farmacianet;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Gestion extends javax.swing.JFrame {
public static String nombre = "";
public static String tipo = "";
public static String cantidad = "";
public static String distri = "";
public static String sucursal = "";
    /**
     * Creates new form Gestion
     */
    public Gestion() {
        initComponents();
        setTitle("FARMACIA NETBEANS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio_distribuidor = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txfnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txfcantidad = new javax.swing.JTextField();
        rbcofarma = new javax.swing.JRadioButton();
        rbemp = new javax.swing.JRadioButton();
        rbceme = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chprincipal = new javax.swing.JCheckBox();
        chsecundaria = new javax.swing.JCheckBox();
        btnconfirmar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("SISTEMA DE PEDIDOS DE MEDICAMENTOS");

        jLabel2.setText("Por favor llene la información solicitada a continuación:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel3.setText("INFORMACIÓN DEL MEDICAMENTO");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("Nombre:");

        txfnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfnombreKeyReleased(evt);
            }
        });

        jLabel5.setText("Tipo:");

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos" }));

        jLabel6.setText("Cantidad:");

        txfcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfcantidadKeyReleased(evt);
            }
        });

        radio_distribuidor.add(rbcofarma);
        rbcofarma.setText("COFARMA");

        radio_distribuidor.add(rbemp);
        rbemp.setText("EMPSEPHAR");

        radio_distribuidor.add(rbceme);
        rbceme.setText("CEMEFAR");

        jLabel7.setText("Distribuidor:");

        jLabel8.setText("Llegada en:");

        chprincipal.setText("Farmacia principal");

        chsecundaria.setText("Farmacia secundaria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chprincipal)
                        .addGap(18, 18, 18)
                        .addComponent(chsecundaria))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfcantidad)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbcofarma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbemp)
                                        .addGap(0, 6, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbceme)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbcofarma)
                    .addComponent(rbemp)
                    .addComponent(rbceme)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chprincipal)
                    .addComponent(chsecundaria))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        btnconfirmar.setBackground(new java.awt.Color(204, 204, 255));
        btnconfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnconfirmar.setText("CONFIRMAR");
        btnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarActionPerformed(evt);
            }
        });

        btnborrar.setBackground(new java.awt.Color(204, 204, 255));
        btnborrar.setText("BORRAR");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarActionPerformed
        // TODO add your handling code here:
        nombre = txfnombre.getText();
        tipo = combotipo.getSelectedItem().toString();
        cantidad = txfcantidad.getText();
        if (nombre.isEmpty()||tipo=="Escoja"||cantidad.isEmpty()||(!rbcofarma.isSelected() && !rbemp.isSelected() && !rbceme.isSelected()) || (!chprincipal.isSelected() && !chsecundaria.isSelected())){
        JOptionPane.showMessageDialog(null, "Falta llenar el formulario","ERROR",JOptionPane.ERROR_MESSAGE);
	}else{
            
            // selección de radio button con el distribuidor
            if (rbcofarma.isSelected()){
            distri = "COFARMA";
            }else if (rbemp.isSelected()){
            distri = "EMPSEPHAR";
            }else {
            distri = "CEMEFAR";
            }
            // Selección del check box con la sucursal
            if (chprincipal.isSelected() && !chsecundaria.isSelected()){
            sucursal = "Para la farmacia situada en Calle de la Rosa n.28";
            }else if (chsecundaria.isSelected() && !chprincipal.isSelected()){
            sucursal = "Para la farmacia situada en Calle Alcazabilla n. 3";
            }else {
            sucursal = "<html>Para la farmacia situada en Calle de la Rosa n.28 y </br> para la situada en Calle Alcazabilla n.3</html>";
            }
            Pedido ventana = new Pedido();
            ventana.setVisible(true);
        }
        
    }//GEN-LAST:event_btnconfirmarActionPerformed

    private void txfnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfnombreKeyReleased
        // Validación de campo nombre a sólo admitir letras
        if(!txfnombre.getText().matches("[aA-zZ,ñÑ, ,áÁ,éÉ,íÍ,óÓ,úÚ,0-9]*")) {
            JOptionPane.showMessageDialog(null, "Sólo se aceptan caracteres alfanuméricos");
            txfnombre.setText("");
	}
    }//GEN-LAST:event_txfnombreKeyReleased

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        //Borrar los parámetros escritos
	//Para jtextField 
	txfnombre.setText("");
	txfcantidad.setText("");
	//Para combobox
	combotipo.setSelectedIndex(0);
	//Para radiobutton
	radio_distribuidor.clearSelection();
	// Para checkbox
	chprincipal.setSelected(false);
	chsecundaria.setSelected(false);
        
    }//GEN-LAST:event_btnborrarActionPerformed

    private void txfcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfcantidadKeyReleased
        // Validación campo cantidad a sólo números
        if (!txfcantidad.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese sólo números enteros");
            txfcantidad.setText("");
            }
    }//GEN-LAST:event_txfcantidadKeyReleased

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnconfirmar;
    private javax.swing.JCheckBox chprincipal;
    private javax.swing.JCheckBox chsecundaria;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup radio_distribuidor;
    private javax.swing.JRadioButton rbceme;
    private javax.swing.JRadioButton rbcofarma;
    private javax.swing.JRadioButton rbemp;
    private javax.swing.JTextField txfcantidad;
    private javax.swing.JTextField txfnombre;
    // End of variables declaration//GEN-END:variables
}
